Make stashes generic over index types
Stebalien/stash-rs pull request #3
Opened 2016-12-17 07:22 UTC by spersson

Inspired by the petgraph library. The reason for a user to choose an index type smaller than usize is probably not to make Entry smaller, since most likely the V type is bigger anyway. The reason is for when storing lots of indices somewhere else, like when building graphs on top of stash. In that case the graph can end up storing lots of indices, so that size may actually matter.
So, one option could have been to keep the next_free field as an usize. I chose not to do that, thinking why not go all the way.
No testing done except from seeing that it compiles on rust 1.13.

2016-12-29 23:36 UTC, Stebalien commented
After thinking about this for a bit, I've decided not to merge as this adds a fair amount of complexity for little gain. Instead, I can guarantee that a stash will "pack" efficiently. This means that if you never insert more than `n` elements in a stash, all indices will be less than `n`. This means that, for example, if you store at most 256 elements, you always safely truncate the index to a u8.

If you disagree, feel free to discuss.

2017-02-23 03:56 UTC, Stebalien commented
So, this came up on #4 and I'm now interested in a simplified version. Specifically, would you be interested in modifying this to work with the following `Index` trait?

```rust
// We need this trait to allow panics when the index is out of range.
pub trait Index {
    // Panics when `idx` is out of range.
    fn from_usize(idx: usize) -> Self;
    fn into_usize(self) -> usize;
}

// Auto implement this for types equivalent to `usize`.
impl<T> Index for T where T: From<usize> + Into<usize> {
    fn from_usize(idx: usize) -> Self {
        From::from(idx)
    }
    fn into_usize(self) -> usize {
        Into::into(self)
    }
}
```

This should simplify this patch significantly.

2017-02-23 13:24 UTC, spersson commented
I might have a bit of time now yes. But I'm unclear on what implementation you have in mind... Because you say that the changes needed would be much less? I really don't see much difference from my proposed changes. The only difference with your trait is dropping the max() function and a few convenience methods. (which is fine with me, those methods could always be added to a newtype index wrapper if needed).
The blanket impl by depending on From and Into traits seems like a great idea!

2017-02-23 16:53 UTC, Stebalien commented
> Because you say that the changes needed would be much less?

The way I'm envisioning it, you'd convert to a usize at the beginning of the function and back to an `Ix: Index` at the end. Internally, you'd store and use `usize`'s.

I'd also hold off on the implementation for `UniqueStash` for now (it doesn't help in your case anyways 
as `Tag` will be quite large due to the `version` field).

2017-02-24 13:49 UTC, spersson commented
I have made changes that compiles without problem now. But I'm a bit stuck on the type inference not working in the tests and examples anymore. I've updated my fork with what I have so far. I will continue looking into what can be done about the current problem, but if you have any advice it would be welcome! And any other comments of course....

2017-02-24 14:20 UTC, spersson commented
I found this post to be informative: http://stackoverflow.com/questions/37748306/default-generic-type-parameter-cannot-be-inferred
So it seems the options are
 1. Accept the loss of ergonomics, user needs to supply type when constructing a Stash. (It's actually the V parameter that is needed now, not Ix... weird.)
 2. Go for the other proposed solution of a separate "default_new" method for constructing an instance using default index type.
 3. Don't make index type a type parameter of the Stash struct, only for the get, take, put methods. Would make it possible to have different index types in calls to get and put on the same stash, which seems not desirable. And I don't know if the current "impl trait" feature would allow us to do this, needed for the put method.

2017-02-24 17:50 UTC, Stebalien requested changes
Looking good, just a few nits.

2017-02-24 17:50 UTC, Stebalien commented on src/stash/mod.rs
> +    _marker: marker::PhantomData<Ix>,
Technically, this should be `marker::PhantomData<fn() -> Ix>` to indicate that we don't actually store any `Ix`s although I'm not sure if it makes any difference...

2017-02-24 17:50 UTC, Stebalien commented on src/stash/mod.rs
> +    _marker: marker::PhantomData<Ix>,
Shoudl probably be `marker::PhantomData<fn(Ix) -> Ix>`.

2017-02-24 17:50 UTC, Stebalien commented on src/stash/mod.rs
>          let loc = self.next_free;
I'd prefer to create the index here (to panic early if necessary): `let idx = Ix::from_usize(self.next_free)`

2017-02-24 17:50 UTC, Stebalien commented on src/index.rs
> +// We need this trait to allow panics when the index is out of range.
Should be documented (even if it's just a short "this is the index trait (auto implemented by usize)...").

2017-02-24 17:56 UTC, Stebalien commented
> But I'm a bit stuck on the type inference not working in the tests and examples anymore.

That's... annoying. However, I'd still like this feature.

>  So it seems the options are

I'm not a fan of 3 and 4. I'm considering a variant of 2 where `new` and `with_capacity` use the default (`usize`) index and introduce additional methods for custom index types but I'll have to think on it a bit.

2017-02-25 07:04 UTC, spersson commented
Ok, I've updated the commit according to your comments and also changed the new() method to only be available for creating Stash with usize index. For creating Stashes with other index types the default() method can be used. This is what petgraph is doing. I also did some minor updates to documentation comments. I'm pretty happy about how it looks now. Confirmed no regression on the benchmarks also.

2017-02-25 21:22 UTC, Stebalien commented
Thanks.

To avoid breaking changes, how do you feel about treating `with_capacity` as a convenience method as well? If you need to specify the index type, you can always write:

```rust
let mut stash: Stash<T, usize> = Stash::default();
stash.reserve(capacity);
```

2017-02-26 17:26 UTC, Stebalien approved these changes

2017-02-26 17:27 UTC, Stebalien commented
Awesome! Thanks!

2017-02-26 17:27 UTC, merged